### ISSUE TITLE
multi accounts support 

### ISSUE THREAD

**Issue by yhsiang** [danielpigott/cloudflare-cli#5]
how about supporting multi accounts?
maybe config in yaml like this
```
defaults: 
  - # user 1
    token: <cloudflare-token>
    email: <user1@domain.com>
    domain: <default-cloudflare-domain>
  -  # user 2
    token: <cloudflare-token>
    email: <user2@domain.com>
    domain: <default-cloudflare-domain>
```

and use `cfcli` like this
`$ cfcli -u [1|user1@domain.com] [other options] command [parameters]`

**Comment by danielpigott** [comment]
This sounds like a good idea, at present you can use a different account by using -c and pointing to an alternate config.  I think I would make the config more like this, so that you could still have a default account:
```
defaults:
  account: work
accounts:
  work:
    token: <cloudflare-token>
    email: <user1@domain.com>
    domain: <default-cloudflare-domain>
  play:
    token: <cloudflare-token>
    email: <user1@domain.com>
    domain: <default-cloudflare-domain>
```

Let me know what you think
